const types = {
  GET_MAP_CENTER: "GET_MAP_CENTER",
  ADD_POINT: "ADD_POINT",
  DELETE_POINT: "DELETE_POINT",
  CHANGE_POINT_POSITION: "CHANGE_POINT_POSITION",
  CHANGE_POINTS_ORDER: "CHANGE_POINTS_ORDER",
  GET_DIRECTIONS: "GET_DIRECTIONS"
};

export default types;
